### PR TITLE
Only user with customize_publish cap can publish snapshot

### PR DESCRIPTION
**Pull request by PatelUtkarsh**

### CODE REVIEW

**Comment by PatelUtkarsh** [comment]
@valendesigns Should we also hide schedule icon in customizer if a user can not publish snapshot?
If do that we might need to allow it on #19 for naming and hide just the calendar UI.

**Comment by westonruter** [comment]
Yes, if the user cannot publish then the scheduling UI should be hidden, I think. It should just allow them to Submit for review (as `pending`) I should think.

**Comment by valendesigns** [comment]
We should definitely close any potential unauthorized means of publishing but retain the ability to see the UI and submit as pending for review.

The client's QA team needs to test features including the scheduling UI so it should not be hidden but limited to what a normal unauthorized user would experience. That means the UI needs to handle a situation where the user doesn't have the privileges, so a save would submit for review (`pending`).

cc @PatelUtkarsh @westonruter

**Comment by westonruter** [comment]
@valendesigns maybe we're saying the same thing, but contributor users cannot assign a date to their posts in the WP admin, so I should think that would apply to contributors in the customizer as well. If they can only create posts with `draft` or `pending` status then they shouldn't be able to assign future dates (and a `future` status) as well:

add_new_post_ _wordpress_develop_5_ _wordpress

**Pull request merged**
