### PR TITLE
Refactor

### LINKED ISSUE #26: Clear up distinction between previewing vs saving values in a snapshot
There seems to be somewhat of a gray area in Customize Snapshots, and in the Customizer in general for previewing vs saving values. In the Customize Snapshots plugin the `can_preview` method is used for both of these conditions, it seems going for the `save` check by seeing if `is_admin()`. I think perhaps they should be separated out a but more to make it more black and white?

``` diff
diff --git a/php/class-customize-snapshot-manager.php b/php/class-customize-snapshot-manager.php
index dab955d..0c1208d 100644
--- a/php/class-customize-snapshot-manager.php
+++ b/php/class-customize-snapshot-manager.php
@@ -305,7 +305,7 @@ class Customize_Snapshot_Manager {
        }

        foreach ( $this->customize_manager->settings() as $setting ) {
-           if ( $this->can_preview( $setting, $this->unsanitized_snapshot_post_data ) ) {
+           if ( $this->can_preview( $setting, $this->unsanitized_snapshot_post_data ) && $setting->check_capabilities() ) {
                $post_data = $this->unsanitized_snapshot_post_data[ $setting->id ];
                $this->snapshot->set( $setting, $post_data['value'], $post_data['dirty'] );
            }
@@ -518,9 +518,6 @@ class Customize_Snapshot_Manager {
        if ( ! ( $setting instanceof \WP_Customize_Setting ) ) {
            return false;
        }
-       if ( ! $setting->check_capabilities() && is_admin() ) {
-           return false;
-       }
        if ( ! array_key_exists( $setting->id, $values ) ) {
            return false;
        }
@@ -538,7 +535,7 @@ class Customize_Snapshot_Manager {
            $this->customize_manager->add_dynamic_settings( array_keys( $values ) );

            foreach ( $this->snapshot->settings() as $setting ) {
-               if ( $this->can_preview( $setting, $values ) ) {
+               if ( $this->can_preview( $setting, $values ) && $setting->check_capabilities() ) {
                    $this->customize_manager->set_post_value( $setting->id, $values[ $setting->id ] );
                }
            }
```

I think maybe the `can_preview` method should be removed entirely?

``` diff
diff --git a/php/class-customize-snapshot-manager.php b/php/class-customize-snapshot-manager.php
index dab955d..6ef1a7d 100644
--- a/php/class-customize-snapshot-manager.php
+++ b/php/class-customize-snapshot-manager.php
@@ -305,7 +305,7 @@ class Customize_Snapshot_Manager {
        }

        foreach ( $this->customize_manager->settings() as $setting ) {
-           if ( $this->can_preview( $setting, $this->unsanitized_snapshot_post_data ) ) {
+           if ( array_key_exists( $setting->id, $this->unsanitized_snapshot_post_data ) && $setting->check_capabilities() ) {
                $post_data = $this->unsanitized_snapshot_post_data[ $setting->id ];
                $this->snapshot->set( $setting, $post_data['value'], $post_data['dirty'] );
            }
@@ -508,26 +508,6 @@ class Customize_Snapshot_Manager {
    }

    /**
-    * Check if the setting can be previewed.
-    *
-    * @param \WP_Customize_Setting $setting A WP_Customize_Setting derived object.
-    * @param array                 $values  All settings' values in the snapshot.
-    * @return bool
-    */
-   public function can_preview( $setting, $values ) {
-       if ( ! ( $setting instanceof \WP_Customize_Setting ) ) {
-           return false;
-       }
-       if ( ! $setting->check_capabilities() && is_admin() ) {
-           return false;
-       }
-       if ( ! array_key_exists( $setting->id, $values ) ) {
-           return false;
-       }
-       return true;
-   }
-
-   /**
     * Set the snapshot settings post value.
     */
    public function set_post_values() {
@@ -538,7 +518,7 @@ class Customize_Snapshot_Manager {
            $this->customize_manager->add_dynamic_settings( array_keys( $values ) );

            foreach ( $this->snapshot->settings() as $setting ) {
-               if ( $this->can_preview( $setting, $values ) ) {
+               if ( $setting->check_capabilities() ) {
                    $this->customize_manager->set_post_value( $setting->id, $values[ $setting->id ] );
                }
            }
@@ -566,7 +546,8 @@ class Customize_Snapshot_Manager {
                $values = $this->snapshot->values();

                foreach ( $this->snapshot->settings() as $setting ) {
-                   if ( $this->can_preview( $setting, $values ) ) {
+                   $is_dirty = array_key_exists( $setting->id, $values );
+                   if ( $is_dirty ) {
                        $setting->preview();
                        $setting->dirty = true;
                    }
```

### LINKED ISSUE #28: Save & Activate button is missing
When doing a live preview of a theme switch, the Save & Activate button is hidden entirely.

### LINKED ISSUE #31: Fail updating a snapshot if any of the setting values are invalid
Add support for https://core.trac.wordpress.org/ticket/34893

### PR DESCRIPTION
**Pull request by westonruter**
Over the past week, off-and-on, I've done a deep dive into the snapshots PHP code and I believe I've come up with an improved refactored codebase that cleans out some cruft and improves mantainability.
- Fixes #28 by ensuring that snapshots UI isn't loaded if a theme switch is happening.
- Fixes #31 by adding support for setting validation.
- Fixes #26 by removing the `can_preview` method.
- Important change: Since scope was removed, now we don't need a `dirty` flag in the post data. We're only storing the changed values. Because of this, we can now simplify the snapshot data to just be the values. We can skip storing a `sanitized` flag as well, however this needs more discovery.
- [ ] Update unit tests to work with newly-refactored codebase.
- [x] Make sure that widget instance data is properly encoded so that it can be re-hydrated.

### CODE REVIEW

**Comment by westonruter** [comment]
@valendesigns please give a 👍 and I'll move forward with using it as the basis for #15

**Comment by valendesigns** [comment]
I'll take a look in an hour or so just wrapping something up.

**Comment by westonruter** [comment]
Closing in favor of PR for `develop`.

**Comment by westonruter** [comment]
New PR to `develop`: https://github.com/xwp/wp-customize-snapshots/pull/59

**Pull request closed without merging**
