### PR TITLE
Add required PHP version go readme

### LINKED ISSUE #159: Add minimum PHP version to readme
See https://twitter.com/TacoVerdo/status/901000997383876609

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #159.

See https://make.wordpress.org/plugins/2017/08/29/minimum-php-version-requirement/

### CODE REVIEW

**Comment by valendesigns** [comment]
@westonruter Shouldn't this be updated in the readme generator in dev-lib?

**Comment by westonruter** [comment]
@valendesigns updated in what way?

**Comment by westonruter** [comment]
The readme generator is copying “Requires PHP” into the markdown version.

**Comment by valendesigns** [comment]
Add `Requires PHP` to this array https://github.com/xwp/wp-dev-lib/blob/master/class-wordpress-readme-parser.php#L41 and inject it into the generated readme.md

**Comment by westonruter** [comment]
It doesn't seem to be required because it works without it.

**Comment by valendesigns** [comment]
I see, so the readme generator is automatically adding `Requires PHP` even though it's not mentioned in the file anywhere. Awesome!

**Comment by westonruter** [comment]
I think the predefined list in the script just ensures that the same order is used when generated.

**Pull request merged**
