### PR TITLE
Release 0.6.0

### PR DESCRIPTION
**Pull request by westonruter**
- [x] Add contributor props.
- [x] Bump version numbers. `ack -Q 0.6.0-rc1` and replace with `0.6.0` where appropriate (this needs to be automated)
- [x] Make sure all unmilestoned PRs and issues are milestoned if fixed in release.
- [x] Add changelog to readme.
- [x] [Draft new GitHub release](https://github.com/xwp/wp-customize-snapshots/releases/new?tag=0.6.0) tag `0.6.0` on `master`, with ZIP build via `grunt build; cd build; zip -r ../customize-snapshots-0.6.0.zip *; cd -; cp customize-snapshots-0.6.0.zip ~/Downloads/customize-snapshots.zip`, and with link to readme on tag tree: https://github.com/xwp/wp-customize-snapshots/blob/0.6.0/readme.md#changelog
- [x] Test build by installing plugin build ZIP.
- [x] Merge release PR.
- [x] Wait for Travis build for [`master` branch](https://travis-ci.org/xwp/wp-customize-snapshots/branches) to go ✅ .
- [x] Deploy to WordPress.org via `grunt deploy`. Remember to look at SVN diff.
- [x] Publish GitHub release.
- [x] Close GitHub milestone.

`pbpaste | sed "s/$PREV_NEW/$NEXT_NEW/g" | sed "s/$PREV_OLD/$PREV_NEW/g" | sed 's:\[x:\[ :'  | pbcopy`

### CODE REVIEW

**Comment by westonruter** [comment]
I was testing this and I came across something unexpected in relation to deleting settings out of a changeset. What I did was:

1. Modify title, tagline, and site icon.
2. Supply a title for the changeset in the Customizer.
3. Click the icon to inspect the changeset in the admin.
4. Delete the change to the `blogname` and hit Save Draft.
5. The result was the `post_content` got wiped out. ⚠️ 
6. Then I tried editing the changeset in the Customizer, but when I tried to save a draft I got a fatal error due to an oversight which is patched in https://core.trac.wordpress.org/ticket/41252

**Comment by westonruter** [comment]
I can't seem to reproduce that anymore.

Another issue I am seeing now. When I publish a changeset from the edit post screen, I then get:

> You can’t edit this item because it is in the Trash. Please restore it and try again.

**Comment by westonruter** [comment]
I see. I was testing on a WP Engine install and revisions are disabled on their platform. That means that changesets don't get prevented from being transitioned to the `trash` status.

**Comment by westonruter** [comment]
Workaround we can add for WPEngine:

```php
add_filter( 'wp_revisions_to_keep', function( $num, $post ) {
    if ( 'customize_changeset' === $post->post_type && 0 === $num ) {
        $num = 1;
    }
    return $num;
}, 10, 2 );
```

**Comment by PatelUtkarsh** [comment]
Bump `tested up to`?

**Pull request merged**
