### PR TITLE
Fix return url in customizer.

### LINKED ISSUE #86: Published snapshot UUID can persist in the customizer exit link
Steps to reproduce:
1. Open customizer
2. Change a setting (e.g. site title)
3. Save snapshot
4. Click to view the snapshot on the frontend: 
   customize__search_results_for_ test _ _wordpress_developsss
5. On the frontend preview, click Customize in the admin bar: search_results_for_ test _ _wordpress_developsss
6. Publish changes.
7. Click ✖️ to close the customizer.

BUG: The snapshot UUID for the _published_ snapshot appears in the URL. It should be stripped when the customizer changes are published.

### PR DESCRIPTION
**Pull request by mohdsayed**
Fixes #86.

### CODE REVIEW

**Review by westonruter — CHANGES_REQUESTED** [review]
@sayedtaqui one more case which I noticed that needs fixing:

1. Make change in customizer.
2. Save Draft
3. Click link preview on frontend
4. Click Customize link in admin bar
5. Problem: Close button has the `customzie_changeset_uuid` query param from the frontend.

I thought that the `customize_changeset_uuid` param was being removed from the `url` param on the Customize link? Maybe it is still only removing `customize_snapshot_uuid`?

**Comment by westonruter** [comment]
On a related note, if the changeset is published (or trashed) and the frontend URL is accessed with that UUID supplied, it should seem that there should also be an HTTP redirect to strip out the snapshot UUID from the URL. I suppose this would also fix the symptom for the above issue but not the underlying cause, although it would fix an issue where someone tries returning to a frontend preview URL after the changeset has been published via another means.

**Comment by mohdsayed** [comment]
@westonruter You mean this https://github.com/xwp/wp-customize-snapshots/issues/86 ?

**Comment by westonruter** [comment]
> You mean this #86 ?

@sayedtaqui why yes! 😄

**Comment by mohdsayed** [comment]
@westonruter `removeParamFromClose()` is a little long but I thought it would be faster than using regex which I had previously written.

```js
removeParamFromClose: function removeParamFromClose( targetParam ) {
    var closeButton, returnURL, newReturnURL, UUID, initial;

    closeButton = $( '.customize-controls-close' );
    returnURL = closeButton.attr( 'href' );
    UUID = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}';
    initial = '\\?';

    if ( returnURL.search( new RegExp( initial + targetParam ), 'g' ) === -1 ) {
        initial = '\\&';
    }

    newReturnURL = returnURL.replace( new RegExp( initial + targetParam + '=' + UUID, 'g' ), '' );

    closeButton.attr( 'href', newReturnURL );
}
```

Ready for review.

**Review by westonruter — APPROVED** [review]

**Pull request merged**
