### PR TITLE
Add filter to button data

### PR DESCRIPTION
**Pull request by jonathanbardo**
While playing around the plugin I noticed it wasn't easy to change the button label or post status choices so I propose to expose a simple filter to do so.

I'm open on feedback on the filter name or if there is another way to approach this!

### CODE REVIEW

**Comment by westonruter** [comment]
@jonathanbardo what are you intending to change the buttons to? I'm concerned about adding a filter at this point since the button UI is still in flux, per https://github.com/xwp/wp-customize-posts/issues/207

**Comment by jonathanbardo** [comment]
@westonruter Sorry for the late reply, I was on vacations 😉 I think the use case would be to remove some options like "future" for example.

**Comment by westonruter** [comment]
There's probably some key overlap with https://core.trac.wordpress.org/ticket/39896

There should be a filter or some core extension mechanism for the statuses that are listed.

**Comment by jonathanbardo** [comment]
@westonruter I agree! We can close this for now.

**Pull request closed without merging**
